{% set name = "scalene" %}
{% set version = "1.5.43.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # See https://pypi.org/project/scalene/#files
  sha256: 145d8c1975e8a534d6b2b2f478435b12fb28899ff7d84535e337f6fa290658d2

build:
  skip: true  # [py<=38]
  number: 0
  entry_points:
    - scalene = scalene.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - cython                                 # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools_scm
    - cython
    - wheel
  run:
    - python
    - astunparse >=1.6.3  # [py<39]
    - rich >=9.2.0
    - cloudpickle >=1.5.0
    - nvidia-ml-py >=12.555.43
    - psutil >=5.9.2
    - jinja2
    - cython

test:
  imports:
    - {{ name }}
  source_files:
    - test/original/bm_mdp.py
  requires:
    - pyperf
    - pip
  commands:
    - pip check
    - scalene --cli test/original/bm_mdp.py
about:
  home: https://github.com/plasma-umass/scalene
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A high-performance, high-precision CPU, GPU, and memory profiler for Python

extra:
  recipe-maintainers:
    - emeryberger
    - jaltmayerpizzorno
    - sternj
