{% set name = "scalene" %}
{% set version = "1.5.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # See https://pypi.org/project/scalene/#files
  sha256: 2b09aa9b3c5e59c87a08db38771cb75fc0b4c504e93b4be2203f01177ca054b0

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - pip
    - setuptools_scm
    - wheel
  run:
    - python
    - rich >=9.2.0
    - cloudpickle >=1.5.0
    - pynvml >=11.0.0
    - jinja2

test:
  imports:
    - {{ name }}
  source_files:
    - test/original/bm_mdp.py
  requires:
    - pyperf
    - pip
  commands:
    - pip check
    - python -m scalene --cli test/original/bm_mdp.py  # [not win]
    - python -m scalene --cli test\\original\\bm_mdp.py  # [win]
about:
  home: https://github.com/plasma-umass/scalene
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A high-performance, high-precision CPU, GPU, and memory profiler for Python

extra:
  recipe-maintainers:
    - emeryberger
    - jaltmayerpizzorno
    - sternj
